### PR TITLE
Adding c-style multiline comments, ca65 supports via .FEATURE c_comments

### PR DESCRIPTION
**Pull request by gavinlynch**
Adding multi-line comments, a la
```
lda #$20
/*
sta $2006
lda #$00
sta $2006
*/
```

enabled via
```
.FEATURE c_comments
```

### CODE REVIEW

**Comment by gavinlynch** [comment]
@maxbane I think I have a fix for the scope regex too. Whatcha think?

**Comment by maxbane** [comment]
This looks great, thanks so much, @gavinlynch! For the scope regex, did you mean as a separate PR?

**Comment by gavinlynch** [comment]
Hey @maxbane, thanks for your quick response and for the merge! I did mean the scope change as a separate PR, but I noticed an issue with it. When I have some spare time to fiddle I'll get it fixed and open a new PR. And thanks for this project!

**Comment by maxbane** [comment]
Thanks @gavinlynch, sounds good! This project is so niche, I'm pleasantly shocked that others find it useful haha.

**Pull request merged**
